// ROOT
:tip-caption: 💡
:note-caption: ℹ️
:important-caption: ⚠️
:task-caption: 🔨
:source-highlighter: pygments
:toc: left
:toclevels: 3
:experimental:
:nofooter:

= Getting Started

[IMPORTANT]
====
Make sure to regularly commit your changes to the repository.
This will allow you to experiment with an easy mind: if things go wrong, you can easily reset it to the last known working version.
====

== Setting Up Visual Studio

[NOTE,caption={task-caption}]
====
* Open the Minesweeper solution in Visual Studio by opening the solution file `Minesweeper.sln`.
* Add a new "Class Library (.NET Core)" to the solution (in the Solution Explorer, right click on the solution at the root of the tree, choose Add &rarr; New Project). Name this project `ViewModel`.
* Add a new "WPF App (.NET)" to the solution. Name it `View`.
* In the Solution Explorer, right click on `View` and select Set as Startup Project.
====

If you press F5 (= run in debug mode), you should be greeted with an empty window.
Next, let's tell these freshly created projects which other projects they can depend upon.

[NOTE,caption={task-caption}]
====
* In the Solution Explorer, right click on Dependencies under ViewModel, pick add Project Dependencies and select Cells and Model. Definitely do *not* select View.
* Add ViewModel as a dependency for View. This way, View will automatically "inherit" the ViewModel's dependencies (i.e., Cells and Model) and will be able to make use of those.
====

This leads to the following dependency structure:

[.center,cols="^,^,^",width="40%"]
|===
3+| View
2+| ViewModel | WPF
| Model | Cell |
|===

where projects can only depend on things *below* them.
In other words:

* The ViewModel must be independent of WPF and the View.
* There are no restrictions imposed on the View: it sees all.

== Creating a Grid

During development, our first goal should be to produce visible results.
The sooner we can see that our code works, the better.
We do not want to have to first write dozens of lines of codes before being able to check their correctness.

In the case of Minesweeper, a logical first step would be to visualize the board.
Unfortunately, this is also the most difficult step of the project.
However, this should not be a problem: this allows this guide to start off with giving you detailed information to help you get past this first obstacle.
The guide will then become less and less detailed as you progress.

=== ItemsControl

The game board is a grid with dimensions W &times; H (W columns, H rows).
Our goal is to visualize this as H rows of W buttons, each button corresponding to one square in the grid.

The easiest way to achieve this is to rely on ``ItemsControl``s.
An `ItemsControl` is a control that allows us to easily visualize lists, where we can specify how each item of the list should be visualized.
Since a grid is essentially a list of lists, we can use similarly nested ``ItemsControl``s to produce a visual grid.

* The top level `ItemsControl` receives a list of H rows.
* We need to tell this top level `ItemsControl` how to render these rows.
  We do this by having it create a new `ItemsControl` for each row.
* Each of these second level ``ItemsControl``s receives a list of W squares.

Let's build towards this structure step by step.
We start off by using an `ItemsControl` in the simplest possible way.

[NOTE,caption={task-caption}]
====
* In `MainWindow.xaml`, add an `ItemsControl` inside the `Grid.
* Give it a name using the `x:Name` property, e.g., `boardView`.
* In `MainWindow.xaml.cs`, create a `List<string>` with some strings in it:
+
[source,csharp]
----
var items = new List<string> { "a", "b", "c", "d", "e" };
----
* Assign this list to `boardView.ItemsSource`. This tells the `ItemsControl` which values it should show.
* Run the project (F5).

A window should appear showing the five strings one below the other.
====

=== ItemTemplate

Right now, the `ItemsControl` uses the default way to render the elements in its `ItemsSource`: it draws them as simple strings.
We would like to turn this into five buttons whose captions are these strings.
For this, we need to make use of the ``ItemsControl``'s `ItemTemplate` property.

[NOTE,caption={task-caption}]
====
* In `MainWindow.xaml`, set the `ItemTemplate` property as follows:
+
[source,diff]
----
  <ItemsControl x:Name="boardView">
+     <ItemsControl.ItemTemplate>
+         <DataTemplate>
+
+         </DataTemplate>
+     </ItemsControl.ItemTemplate>
  </ItemsControl>
----
* The `DataTemplate` represents how each element must be rendered.
  Place a `Button` in here.
+
[source,diff]
----
  <ItemsControl x:Name="boardView">
      <ItemsControl.ItemTemplate>
          <DataTemplate>
+             <Button />
          </DataTemplate>
      </ItemsControl.ItemTemplate>
  </ItemsControl>
----
* Run the code (F5).

A window with five very narrow buttons should appear.
====

The buttons' small height is due to the fact that we have not given them a label.
Let's rectify this:

[NOTE,caption={task-caption}]
====
* Give the `Button` a caption. Let's keep it simple for now and use `Click me`.
+
[source,diff]
----
  <ItemsControl x:Name="boardView">
      <ItemsControl.ItemTemplate>
          <DataTemplate>
-              <Button />
+              <Button Content="Click me" />
          </DataTemplate>
      </ItemsControl.ItemTemplate>
  </ItemsControl>
----
* Run your code (F5).

You should see five buttons, each labeled `Click me`.
====

Next, instead of labeling each button `Click me`, we want them to show the strings in the `ItemsSource`.

The `ItemsControl` instantiates the `ItemTemplate` for each of the elements in `ItemsSource`, in our case a `Button`.
It also sets the `DataContext` of each of these ``Button``s: the first `Button` will have `"a"` as `DataContext`, the second `"b"`, and so on.
In other words, each `Button` can rely on its `DataContext` to know which element it corresponds to.

[NOTE,caption={task-caption}]
====
Update the `Button`'s `Content` so that it shows the value of its `DataContext.

[source,diff]
----
  <ItemsControl x:Name="boardView">
      <ItemsControl.ItemTemplate>
          <DataTemplate>
-              <Button Content="Click me" />
+              <Button Content="{Binding .}" />
          </DataTemplate>
      </ItemsControl.ItemTemplate>
  </ItemsControl>
----

Here, `{Binding .}` means "use the `DataContext` itself".

Run your code. You should see five buttons, labeled `a`, `b`, `c`, `d` and `e`.
====

=== ItemsPanel

The buttons are laid out vertically.
In order to render the rows, we need them to be arranged horizontally instead.
Lucky for us, the `ItemsControl` has a property `ItemsPanel` which determines how the buttons will be positioned.

[NOTE,caption={task-caption}]
====
[source,diff]
----
  <ItemsControl x:Name="boardView">
      <ItemsControl.ItemTemplate>
          <DataTemplate>
              <Button Content="{Binding .}" />
          </DataTemplate>
      </ItemsControl.ItemTemplate>
+     <ItemsControl.ItemsPanel>
+         <ItemsPanelTemplate>
+             <StackPanel Orientation="Horizontal" />
+         </ItemsPanelTemplate>
+     </ItemsControl.ItemsPanel>
  </ItemsControl>
----

By default the `ItemsControl` uses a `StackPanel` with `Orientation="Vertical"`.
The above code changes this to a `StackPanel` with `Orientation="Horizontal"`.

Run your code.
The buttons should now be arranged horizontally instead of vertically.
====

=== Going 2D

We now have all ingredients to be able to show a grid.

[NOTE,caption={task-caption}]
====
Start with creating grid data in ``MainWindow``'s constructor in `MainWindow.xaml.cs`.

[source,csharp]
----
var row1 = new List<string> { "a", "b", "c", "d", "e" };
var row2 = new List<string> { "e", "f", "g", "h", "i" };
var row3 = new List<string> { "j", "k", "l", "m", "n" };
var grid = new List<List<string>> { row1, row2, row3 };

this.boardView.ItemsSource = grid;
----

If you run your code, you should see three horizontally arranged buttons.
Each `Button` has a `List<string>` as `DataContext`, which is also uses as `Content`.
Since WPF does not know how to render these, it decides to improvise.
====

Now comes the tricky part: we need to visualize this grid.

[NOTE,caption={task-caption}]
====
* Go to `MainWindow.xaml`.
* Put your current `ItemsControl` in comments, so that you can reuse parts of it.
* Add code that creates a fresh `ItemsControl`.
  This will be the top level `ItemsControl` that's in charge of visualizing all rows.
  Remember that its `ItemsSource` is set to `grid`, i.e., a `List<List<string>>`.
* This top level `ItemsControl` should lay out its children *vertically*. Since this is the default, you do not need to specify a new `ItemsPanel`.
* Next, add code that sets its `ItemTemplate`.
* Inside this `ItemTemplate`, again create an `ItemsControl`. This one will be responsible to render a single row.
* Have this inner `ItemsPanel` arrange its items *horizontally*.
* Have its `ItemTemplate` be a `Button`.
* For now, set this ``Button``'s `Content` to simply `x`.
* Lastly, we must set the inner ``ItemControl``'s `ItemsSource`.
  We know that the outer `ItemsControl` has set its `DataContext` to a row, i.e., a `List<string>`.
  So, we should simply bind the inner ``ItemControl``'s `ItemsSource` to this `DataContext`: `ItemsSource={Binding .}`.

Run your code.
You should see a 3 rows of 5 buttons, all labeled `x`.
====

Instead of having every `Button` show `x`, we want them to show their corresponding letter.

[NOTE,caption={task-caption}]
====
Adjust the ``Button``'s `Content` so that it shows the correct letter instead of `x`.
Think of what each ``Button``'s `DataContext` is set to.
Remember that there are ways to find out what its value is if you're in doubt.
====

Each button has a different size, due to the letters having varying sizes.
For Minesweeper, it'd be easier to play if each button had the same size.

[NOTE,caption={task-caption}]
====
Set the ``Button``'s `Width` and `Height` to `32`.
====

== IGame

Currently, we have defined our own grid data.
In this section, we will start relying on domain classes.
Let's explore these for a bit.

A game is by an object implementing the `IGame` interface.
This interface contains all Minesweeper-related functionality.
To create a game, `IGame` offers a static factory method:

[source,csharp]
----
var game = IGame.Create(boardSize, flooding, seed)
----

where

* `boardSize` is an `int` representing the size of the board.
* `flooding` is a `bool` determining whether or not flooding is enabled.
* `seed` is an `int` that deterministically generates the board.

Right now, we are interested in the board.
We can access this using the `Board` property:

[source,csharp]
----
var board = game.Board;
----

It should not come as a surprise that this `board` contains all information related to the game board.

[source,csharp]
----
// Querying width
var width = board.Width;

// Querying height
var height = board.Height;

// Querying square
var position = new Vector2D(0, 0);
var square = board[position];
----

In order for our `ItemsControl` construction to be able to work with this board, we need to restructure the data as a list of lists.

[NOTE,caption={task-caption}]
====
In `MainWindow.xaml.cs`, add the following methods to the `MainWindow` class:

* Write a method `IEnumerable<Square> Row(IGameBoard board, int row)` that returns a `List<Square>` containing all squares on the ``row``th row of `board`.
* Write a method `IEnumerable<IEnumerable<Square>> Rows(IGameBoard board)` that calls `Row` for every row on `board` and returns the results as a list.
  In other words, this method returns a list of the rows of `board`.
* In the `MainWindow` constructor:
** Get rid of the old `List<List<string>>` related code.
** Create an `IGame` object with board size `6` (flooding and seed don't matter).
** Use `Rows` to turn the ``IGame``'s `Board` into a `IEnumerable<IEnumerable<Square>>`.
** Use this last result as the outer ``ItemsControl``'s `ItemsSource`.

Run your code.
You should see 6&times;6 buttons without label.
====

The missing label is due to the fact that initially nothing is visited.
In other words, the `IEnumerable<IEnumerable<Square>>` is populated with empty string values.

=== Visualize Squares

Next, we want to visualize our squares.
For this, we need to visit some squares on the game board.

[NOTE,caption={task-caption}]
====
In `MainWindow.xaml.cs`, use the game's `UncoverSquare` method to visit some squares.
Note that the `IGame` object is stateless, meaning you cannot modify it.
`UncoverSquare` returns a *new* `IGame` object instead of modifying it.

Run your code.
If you did it correctly, you should see squares containing `0-8` or `B`.
====

The text appears because we're asking WPF to draw `Square` objects, but these are unknown to WPF.
In such cases, WPF chooses to call to `ToString()` method and render the result.
If you look at the implementation of `Square`, you will see that the `ToString()` method does indeed return `0-8`, `F` or `B`, depending on where bombs are placed.

== Introducing ViewModels

As of yet, we have only written code in the View.
It is time we clean up our design and refactor a bit by moving things to the ViewModel layer.

ViewModel objects generally act as ``DataContext``s for GUI controls: they contain all information the control needs.
The goal of this approach is to build a layered structure:

* The ViewModel objects "passively" offers information through properties.
* The View will fetch this ViewModel data through bindings.

At no times should the ViewModel know anything about what exists on the View layer.

=== Unnaming the ItemsControl

The top level `ItemsControl` currently has a name: its `x:Name` property is set in the XAML code.
We needed this to be able to initialize its `ItemsSource` in the `MainWindow` constructor:

[source,csharp,highlight=10]
----
public MainWindow()
{
    InitializeComponent();

    var game = IGame.Create(5, true);

    game = game.UncoverSquare(new Vector2D(0, 0));
    game = game.UncoverSquare(new Vector2D(1, 0));

    this.boardView.ItemsSource = Rows(game.Board);
}
----

This approach is not ideal: it stands in our way of introducing ViewModels.
Instead, we would prefer that the control fetches its `ItemsSource` from its `DataContext` instead of us setting it explicitly in the code-behind.
Fortunately, this is easy to fix.

[NOTE,caption={task-caption}]
====
Instead of assigning the row data to ``boardView``'s `ItemsSource`, assign it to the ``MainWindow``'s `DataContext`.
The `ItemsControl` will then inherit its `DataContext` from `MainWindow`.

In the XAML file, remove the ``ItemsControl``'s name. Use a binding to set its `ItemsSource` to its `DataContext`.

Run the code to check that everything still works.
====

=== GameViewModel

As explained earlier, ``DataContext``s should be set to ViewModel objects.
Let's see what ``DataContext``s we have.

* The top level ``ItemsControl``'s `DataContext` is set to the grid data, i.e., an `IEnumerable<IEnumerable<Square>>`.
* The inner ``ItemsControl``s each receive an `IEnumerable<Square>` as `DataContext`.
* Each button has a single `Square` as `DataContext`.

Let's wrap each of these in ViewModel objects, one at a time, starting with the top level `ItemsControl`.
Our current situation is

image::itemscontrol-directbinding.svg[Static,400,align="center"]

Our goal is to reorganize this as follows:

image::itemscontrol-gamevm.svg[Static,600,align="center"]

[NOTE,caption={task-caption}]
====
In The ViewModel, introduce a class `GameViewModel`.
We intend this class to contain all game related data.
For now, we will limit ourselves to have it expose the board so that the View can render its grid of buttons.

* Have the constructor accept an `IGame` object and have it stored in a private field.
* The top level `ItemsControl` needs rows, so introduce a public `Rows` property.
  It must have type `IEnumerable<IEnumerable<Square>>`.
  It should be only gettable, not settable.
* You might want to bring along the `Row` helper method that extracts a single row from the board.

Next, update the `MainWindow` constructor.

* Keep the code that creates the `IGame` object and visits some squares around.
* Create a `GameViewModel` object and initialize it with the `IGame` object.
* Assign this `GameViewModel` object to the ``MainWindow``'s `DataContext`.
* Remove the `Row` and `Rows` methods from the `MainWindow` class, that functionality has been moved to `GameViewModel`.

Finally, in the XAML file, update the ``ItemsControl``'s `ItemsSource` binding.
It used to receive the rows directly as `DataContext`, but now they are stored inside a `GameViewModel` object's `Rows` property.

As always, run the code.
The same 6 &times; 6 grid of buttons should still appear.
====

=== GameBoardViewModel

Right now, the `GameViewModel` actually represents the board.
We would like to distinguish the game from its game board.
Let's create a separate `GameBoardViewModel` class.

image::itemscontrol-gamevm-boardvm.svg[Static,700,align="center"]

[NOTE,caption={task-caption}]
====
In the ViewModel, introduce a class `GameBoardViewModel`.

* The constructor expects a `IGameBoard` object, which it stores in a private field.
* Move the `Rows` property (and its helper methods, if any) from `GameViewModel` to `GameBoardViewModel`.

Update `GameViewModel`:

* Introduce a public property `Board` of type `GameBoardViewModel`, getter-only.
* Initialize this property in the constructor.

[IMPORTANT]
=====
Do not have the `Board` getter create a new `GameBoardViewModel` each time.
Make sure to create it only once, namely in the constructor, and have `Board` return it.
=====

Lastly, update the `ItemsSource` binding:

* It starts off in the `DataContext`, which is a `GameViewModel`.
* The binding needs to first go to its `Board` property.
  Then it must dig on step deeper to the board's `Rows` property.

Run it and check that nothing has changed.
====

=== GameBoardRowViewModel

Next in line is a ViewModel representing a board row.

[NOTE,caption={task-caption}]
====
Introduce a class `GameBoardRowViewModel`.

* The constructor expects a `IEnumerable<Square>`.
* The `IEnumerable<Square>` is exposed through a property named `Squares`.
* Update the `Rows` property of `GameBoardViewModel`: instead of returning `IEnumerable<IEnumerable<Square>>`, it now returns a `IEnumerable<GameBoardRowViewModel>`.
* Update the bindings of the inner ``ItemsControl``s.
  Their `DataContext` has now changed from `IEnumerable<Square>` to `GameBoardRowViewModel`, so the binding will need to access the `Squares` property of its `DataContext`.

Run it and check that nothing has changed.
====

image::itemscontrol-rowvm.svg[Static,700,align="center"]

=== GameBoardSquareViewModel

Lastly, we want a ViewModel object for each square of the grid.
We will call this `GameBoardSquareViewModel`.

image::itemscontrol-squarevm.svg[Static,700,align="center"]

[NOTE,caption={task-caption}]
====
Introduce a class `GameBoardSquareViewModel`.

* The constructor expects a `Square`.
* The `Square` is exposed through a property named `Square`.
* Update `GameBoardRowViewModel` so that `Squares` returns an `IEnumerable<GameBoardSquareViewModel>` instead of an `IEnumerable<Square>`.
* Update the binding for ``Button``'s `Content` property.

Run it and check that nothing has changed.
====

We're finally done with refactoring and can again start adding new functionality.

== Uncovering Squares

=== UncoverSquareCommand

We would like to be able to uncover squares on the game board by clicking on the corresponding button.
This can be achieved by adding a command to the `GameBoardSquareViewModel`.
Let's start small.

[NOTE,caption={task-caption}]
====
* In the ViewModel, define a `UncoverSquareCommand` class that implements `ICommand`.
* Have the `Execute` method print a debug message.
+
[source,csharp]
----
Debug.WriteLine("You clicked me");
----
* `CanExecute` can for now always return `true`.
* In `GameBoardSquareViewModel`, add a `UncoverSquare` property of type `ICommand`, getter only.
* Initialize this `UncoverSquare` property in the constructor.
* In `MainWindow.xaml`, update the `Button` so that pressing it invokes `UncoverSquare`.

Run it.
Whenever you click a button, `You clicked me` should appear in the output pane.
====

=== Passing Along IGame

We would like to implement ``UncoverSquareCommand``'s ``Execute` method, but we run into a number of issues.
We'll deal with each in turn.

The functionality for visiting squares resides in the `UncoverSquare` method of `IGame`.
This means `UncoverSquareCommand` would need access to the `IGame`, but currently it only receives a measly `Square`.
However, we know the `GameViewModel` object holds the `IGame`.
We will have to pass it along to all intermediate ViewModel classes so that the `IGame` might reach `UncoverSquareCommand`.

As always, let's do this step by step.

[NOTE,caption={task-caption}]
====
Currently, `GameBoardViewModel` receives only an `IGameBoard`.

* Its constructor should receive an `IGame` instead of an `IGameBoard`.
* In the constructor, retrieve the `IGameBoard` from the `IGame`.

Note that `GameBoardViewModel` does *not* need to save the `IGame` itself in a field; saving the `IGameBoard` is sufficient.

Run your code after this step.
Everything should still work.
====

[NOTE,caption={task-caption}]
====
Next, we need to let `GameBoardViewModel` pass the `IGame` along to `GameBoardRowViewModel`.
Add an extra `IGame` parameter to its constructor and update `GameBoardViewModel` accordingly.
Right now, `GameBoardViewModel` doesn't need to do anything with this `IGame`.

Run your code and check that everything works.
====

[NOTE,caption={task-caption}]
====
Now we have `GameBoardRowViewModel` pass the `IGame` to `GameBoardSquareViewModel.`
At this stage, `GameBoardSquareViewModel` needn't do anything with the `IGame`.

Again, run your code.
====

[NOTE,caption={task-caption}]
====
Finally, have `GameBoardSquareViewModel` give the `IGame` to `UncoverSquareCommand`.
`UncoverSquareCommand` will have to store the `IGame` in a field.

Yes, run your code, yet again.
====

=== Square Position

Now that `UncoverSquareCommand` finally has access to the `IGame`, we should be able to call its `UncoverSquare` method.
However, there's a catch: the `UncoverSquare` method needs to know _where_ to visit.
Right now, `UncoverSquareCommand` has no clue about which square on the board it is associated with.

It is important to realize that there as many `UncoverSquareCommand` objects as there are squares on the board: each button in the view has its very own `UncoverSquareCommand`.
This means we can tell each such object where it is positioned.

[NOTE,caption={task-caption}]
====
Let's start at the bottom first, i.e., `UncoverSquareCommand`.

* Add a `Vector2D` field named `position` to `UncoverSquareCommand`.
* Add an extra constructor parameter.

We go up one level, to `GameBoardSquareViewModel`.
It represents one square, so it makes sense for it to also have a position associated with it.

* Add a new constructor parameter `Vector2D position`.
* Remove the `Square square` parameter.
  Instead, let the constructor itself look up the square using the provided `IGame` and `Vector2D`.
* Pass the position along to the `UncoverSquareCommand` constructor.

Now it's ``GameBoardRowViewModel``'s turn.
Since it is a full row, we can only give it its `y` coordinate.

* Have the constructor accept only an `IGame game` and an `int y`.
  This information should be sufficient to initialize its `Squares` property: for each square on row `y` of `game.Board`, it must create `GameBoardSquareViewModel`.

Lastly, `GameBoardViewModel`.

* Update this class so that it gives each `GameBoardRowViewModel` its corresponding `y` coordinate.

Run your code and check that everything still works.
====

We'd like to make sure each `UncoverSquareCommand` does indeed receive its position.
Let's make a quick change to check this.

[NOTE,caption={task-caption}]
====
Have `UncoverSquareCommand` print its position instead of `You clicked me`.

Run the program, click on buttons and check that the right coordinates are outputted.
====

== Reactive Programming

Now that `UncoverSquareCommand` has both the `IGame` object and its position, surely we're ready to make it work?
Sadly, there's still one problem: ``IGame``'s `UncoverSquare` does not modify the object, but returns a new one.
We clearly need to do _something_ with this new `IGame` object, but what?

The new `IGame` object contains an updated board.
This means that all ``GameBoardSquareViewModel``s should update their `Square` property.
However, the `UncoverSquareCommand` object has no way of contacting each `GameBoardSquareViewModel`.
We could of course give each `UncoverSquareCommand` object a list of all existing ``GameBoardSquareViewModel``s so that it can ask them to refresh themselves.
Fortunately, there is a much easier solution.

Note that not only do we need the ``GameBoardSquareViewModel``s to update their `Square` property, we also need the View to be aware of this change.
Without some kind of notification, the View will not know of this update and therefore not see any reason of updating itself.

This is where Reactive Programming shows its strength.
In short, Reactive Programming consists of having variables automatically update themselves whenever another variable changes.
Consider this example:

[source,csharp]
----
var x = 1;
var doubleOfX = x * 2;
x = 5;
----

After the execution of the last statement, `doubleOfX` will be equal to `2`, even though `x` equals `5`.
Wouldn't it make more sense for `doubleOfX` to be `10`?

The reason for this, of course, is that `doubleOfX` has been initialized at a time where `x` was still `1`.
Changing `x` does not cause `doubleOfX` to be magically updated alongside with it.

Reactive Programming involves creating variables that _do_ update themselves automatically.
For example,

[source,csharp]
----
var x = 1;
var doubleOfX = x * 2; // doubleOfX == 2
x = 5;                 // doubleOfX == 10
x = 2;                 // doubleOfX == 4
x = 7;                 // doubleOfX == 14
----

However, Reactive Programming is not built into C#.
This is where Cells come in: these can be used to "fake" Reactive Programming.

[source,csharp]
----
var x = Cell.Create(1);
var doubleOfX = x.Derive(k => k * 2); // doubleOfX.Value == 2
x.Value = 5;                          // doubleOfX.Value == 10
x.Value = 2;                          // doubleOfX.Value == 4
x.Value = 7;                          // doubleOfX.Value == 14
----

Here, `Derive` creates a new element that is kept in sync with the original element.
The lambda `k => k * 2` expresses how `doubleOfX` is related to `x`:

* The parameter `k` contains the value of the original element (`x`).
* The body `k * 2` tells how to compute the derived element's value (`doubleOfX`).

Let's see how we can leverage Reactive Programming in the case of Minesweeper.

=== Cell

Say we start off with an `ICell<IGame>` in which we store the current game state.

[source,csharp]
----
var currentGame = Cell.Create(IGame.Create(5, true));
----

From this we can derive the game board:

[source,csharp]
----
var currentGameBoard = currentGame.Derive(g => g.Board);
----

We can then create a derived element that contains the square in the upper left corner of the board:

[source,csharp]
----
var upperLeftCorner = currentGameBoard.Derive(b => b[new Vector2D(0,0)]);
----

Initially, `upperLeftCorner.Value` will be covered, since that square hasn't been visited yet.
Say we visit there:

[source,csharp]
----
// Uncovering a square
currentGame.Value = currentGame.Value.UncoverSquare( new Vector2D(0, 0) );
----

It is important that you understand what is going on here:

* We retrieve the current game from the cell: `currentGame.Value` in the right side of the assignment.
* We call `UncoverSquare` on this `IGame` object.
* This returns a new `IGame` object.
* We store this new `IGame` object in the `currentGame` cell.
* The change in `currentGame` causes `currentGameBoard` to be updated.
* `upperLeftCorner` is aware of this change and fetches its new value from the board: `Uncovered or Mine`.

We can create one derived cell per square and wrap each one in a `GameBoardSquareViewModel` object.

image::game-cell.svg[Static,600,align="center"]

Using cells takes care of two issues at once:

* We don't need to manually update all ``GameBoardSquareViewModel``s `Square` property anymore: this is done automatically by derived cells.
* WPF "understands" cells (because they implement the `INotifyPropertyChanged` interface). Whenever a cell's value changes, WPF will know that it will need to rerender the view.

It is now time for you to introduce cells in your code.

[NOTE,caption={task-caption}]
====
* `GameViewModel`
** Its constructor receives an `IGame` and stores it in a field with type `IGame`.
** Change the field type to `ICell<IGame>` and update the constructor correspondingly.
   Note that the parameter type should remain simply `IGame`.
* `GameBoardViewModel`
** In `GameBoardViewModel`, update the `board` field's type from `IGameBoard` to `ICell<IGameBoard>`.
** Its constructor should now accept an `ICell<IGame>` instead of an `IGame`.
** From this cell, derive an `ICell<IGameBoard>` and store it in the field.
* `GameBoardRowViewModel`
** Its constructor should now receive an `ICell<IGame>`.
* `GameBoardSquareViewModel`
** The constructor receives an `ICell<IGame>`.
** Change the `Square` property's type to `ICell<string>` by using the ToString() method while deriving.
** In the constructor, initialize it to a derived cell that contains the `Square` at the appropriate position.
* `UncoverSquareCommand`
** Its constructor should also receive the `ICell<IGame>` and store it in a field.
* XAML code
** Update the `Content` binding. Since we upgraded property `Square` from type `Square` to `ICell<string>`, the binding needs to change from `Square` to `Square.Value`.

Run your code and check that everything still works the same.
====

=== Making it Work

We are finally ready to uncover squares on the board.

[NOTE,caption={task-caption}]
====
In ``UncoverSquareCommand``'s `Execute` method, call the ``IGame``'s `UncoverSquare` and store its result back into the cell.

Run the code.
You should be able to uncover squares.
====

== Invalid Moves

If you click on a cell which has been uncovered already, the program will crash.
This is due to `UncoverSquare` throwing an exception when you're making an invalid move.

=== CellCommand

Commands exist specifically to make it possible to disable them: if `CanExecute` is `false`, the button will block all clicks, which is exactly what we need.
We would also need to signal `CanExecuteChanged` when ``CanExecute``'s result changes.

This is more or less what cells do: they have values and broadcast a signal when this value changes.
It'd be nice to also rely on cells when dealing with commands.
Let's implement a command class that does exactly that.

[NOTE,caption={task-caption}]
====
* In the ViewModel, create a new class named `CellCommand`.
* Have it implement `ICommand`, i.e., have Visual Studio generate stubs.
* The constructor should receive a parameter `ICell<bool> canExecute`.
* This `canExecute` cell should be stored in a field.
* Have `CanExecute` return the contents of the cell.
* When the cell changes value, `CanExecuteChanged` needs to be called. In the `CellCommand` constructor, add
+
[source,csharp]
----
this.canExecute.ValueChanged += () => CanExecuteChanged?.Invoke(this, new EventArgs());
----
** `() => CanExecuteChanged?.Invoke(this, new EventArgs())` is an anonymous function that takes no parameters (represented by `()` before the arrow) and has as body `CanExecuteChanged?.Invoke(this, new EventArgs())`.
** The `?.` operator first checks if `CanExecuteChanged` is `null`. If so, the call to `Invoke` is not made since it would lead to a `NullReferenceException`.
====

All that remains to be implemented is the `Execute` method.
We could leave it abstract and expect users to subclass our `CellCommand`.
A more user-friendly solution would be to let the user pass along the code for `Execute` as a constructor parameter.

[NOTE,caption={task-caption}]
====
* Add an extra parameter `Action execute` to ``CellCommand``'s constructor.
* Store it in a field.
* Call it in the `Execute` method.
====

=== Revisiting UncoverSquareCommand

Let's rewrite `UncoverSquareCommand` so as to make use of this `CellCommand`, still ignoring move validity for now.

[NOTE,caption={task-caption}]
====
In ``GameBoardSquareViewModel``'s constructor

* Add a local variable `ICell<bool> isValidMove` that is simply initialized to `true`.
  We will have to fix this in a later step.
* Initialize `PutStone` with a `CellCommand`.
  The `execute` parameter should be set to a lambda that contains the same code as ``UncoverSquareCommand``'s `Execute` method.
* Remove `UncoverSquareCommand` altogether.

Run your code.
Everything should still work as before, i.e., it should still be possible crash the game by putting a stone in an already occupied crash.
====

We now introduce the move validity check.

[NOTE,caption={task-caption}]
====
In ``GameBoardSquareViewModel``'s constructor

* Set `isValidMove` to a cell of type `ICell<bool>` that derives from `game`.
  Its contents should reflect whether it is valid to uncover at the square's position.
  Look in `IGame` for methods that could prove useful.

Run your code.
The application should not crash anymore when attempting to uncover a square that has already been uncovered.
====

== Drawing Squares

=== Giving Color

Right now, we draw each square using

[source,xml]
----
<Button Content="{Binding Square.Value}" Width="32" Height="32" />
----

In other words, we tell the `Button` that its contents are equal to its `DataContext`, which itself is equal to a `string`. But we're setting this using the `ToString()` method to fill in the text from the ViewModel, and per requirements strings passed from Model or ViewModel are not allowed. So lets draw something starting from Square ourselves.

[NOTE,caption={task-caption}]
====
In `MainWindow.xaml`, change the button to

[source,xml]
----
<Button Width="32" Height="32" Command="{Binding UncoverSquare}">
    <Grid Width="24" Height="24">
        <Ellipse Stroke="red"/>
        <TextBlock HorizontalAlignment="Center" Text="0" TextAlignment="Center" VerticalAlignment="Center"/>
    </Grid>
</Button>
----

Run the code.
Every button should now contain a small red circle with a 0 in the middle.
====

=== SquareConverter

Next step is to have the ``Ellipse``'s `Fill` and ``TextBlock``'s `Text` vary according to the state of a square, there are 4 possible states:

[.center,cols="^,^,^",options="header",width="80%"]
|===
| Square State | Ellipse Fill Brush | Text
| Covered | Transparent | None
| Uncovered | Transparent | #AdjacentMines
| Flagged (& covered) | Orange | None
| Mine (& uncovered) | Black | None
|===

To convert from `Square` to `Brush` and `string`, we need to create an `IValueConverter`. But `IValueConverter` only accepts one input while we require atleast two arguments: the state of the square and the amount of adjacent mines. We also can not give Square itself as input since it doesn't have these properties. Instead we can use a `wrapper` class that exposes these 2 values as properties and pass an instance of that class to the converter.

[source,csharp,highlight=10]
----
public class SquareWrapper()
{
    public bool IsCovered { get; }
    public bool IsMine { get; }
    public bool IsFlagged { get; }

    public int AdjacentMines { get; }

    public SquareWrapper(IGame game, Vector2D position)
    {
        ...
    }
}
----

[NOTE,caption={task-caption}]
====
* Implement SquareWrapper in the ViewModel project using functions from IGame. Handle functions that throw errors properly without try-catch.
* In GameBoardSquareViewModel, change the type of property Square from `ICell<string>` to `ICell<SquareWrapper>`
* Add a new folder named `Converters` to your View project.
* Add a new class file named `SquareColorConverter.cs` to this folder.
* Have `SquareColorConverter` implement `IValueConverter`, i.e., have Visual Studio generate stubs.
* In the `Convert` method
** The first parameter `value` corresponds to the `wrapper`.
   It has type `object`, but that's not a problem.
   We can simply cast the object to the type `SquareWrapper`.
** If `wrapper.IsMine`, return `Brushes.Black`.
** If `wrapper.IsFlagged`, return `Brushes.Orange`.
** If `wrapper.IsCovered`, return `Brushes.Transparent`.
** If `!wrapper.IsCovered`, return `Brushes.Transparent`.
====

We can now use this converter.

[NOTE,caption={task-caption}]
====
In `MainWindow.xaml`:

* We want to access `SquareColorConverter`, which resides in the `View.Converters` namespace.
  For this, we need to add an extra namespace mapping.
  Add the following attribute to `Window` (the top element):
+
[source,diff]
----
  <Window ...
          xmlns:local="clr-namespace:View"
+         xmlns:converters="clr-namespace:View.Converters"
          ...>
----
* Create the `SquareColorConverter` as a resource.
+
[source,diff]
----
  <Window ...>
+     <Window.Resources>
+         <converters:SquareColorConverter x:Key="squareToBrushConverter" />
+     </Window.Resources>
      ...
  </Window>
----
* Bind `Stroke` to the `DataContext` itself.
  Have it https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/staticresource-markup-extension[use] `squareToBrushConverter` as converter.

Run your code.
If you did everything correctly, you will see 0's everywhere but if you hit a mine, the mines will appear as circles.
====

=== Generalizing SquareColorConverter

Hardcoding the colors in `SquareColorConverter` is actually a bad idea:

* We can easily generalize it so that it becomes reusable.
* The color of the squares should be determined by an artist, not a programmer.
  Specifying the color in C# code is not very artist-friendly: they'd rather define everything in XAML.
* If we need more elaborate brushes, it's easier to define them in XAML than in C#.

So let us improve our `SquareColorConverter`.

[NOTE,caption={task-caption}]
====
In `SquareColorConverter`:

* Add four properties `Covered`, `Uncovered`, `Flagged` and `Mine`. Each has type `object` and has both a getter and setter.
* In the `Convert` method, return the values of `Covered`, `Uncovered`, `Flagged` and `Mine` instead of hardcoded brushes.

In `MainWindow.xaml`, initialize the four properties of the `SquareColorConverter`.
[source,diff]
----
  <Window ...>
      <Window.Resources>
-         <converters:SquareColorConverter x:Key="squareToBrushConverter" />
+         <converters:SquareColorConverter x:Key="squareToBrushConverter"
+                                    Covered="Transparent"
+                                    Uncovered="Transparent"
+                                    Flagged="Orange"
+                                    Mine="Black" />
      </Window.Resources>
      ...
  </Window>
----

* Create a second converter `SquareTextConverter` to fill in the `Text` of `TextBlock` so that it only shows adjacent mines when uncovered.
====

Run your code and check that everything works as intended.

== Flagging Squares

Now we got most of Minesweeper core functionalities working, we're still missing flags.
In Minesweeper, it is the tradition to flag a square using the right mouse button, for that we'll need to add an InputBinding to the button.

[source,xml]
----
<Button Width="32" Height="32" Command="{Binding UncoverSquare}">
    <Grid Width="24" Height="24">
        <Button.InputBindings>
            <MouseBinding Gesture="RightClick" Command="{Binding FlagSquare}" />
        </Button.InputBindings>
        ...
    </Grid>
</Button>
----


[NOTE,caption={task-caption}]
====
* Add the gesture RightClick to the button's InputBindings as above
* Implement the FlagSquare command, the method `IGame.FlagSquare` acts as a toggle: use the same method to turn it `on` and `off`.
====

Run your code and check that flags are working.

The guide ends here but you are not at the project minimum requirements just yet.
Head over to the <<requirements.asciidoc#,Requirements>> page to see what more you can do.