// ROOT
:tip-caption: 💡
:note-caption: ℹ️
:important-caption: ⚠️
:task-caption: 🔨
:source-highlighter: pygments
:toc: left
:toclevels: 3
:experimental:
:nofooter:

# Setup Instructions

On Toledo, a link should be provided to GitHub Classroom.
Go there and accept the assignment.
This will create a brand new repository just for you.
You can clone this repository to your laptop:

[source,bash]
----
# Needs to happen only once
$ git clone URL minesweeper
----

where `URL` is replaced by the URL of your fork.
This will create a directory `minesweeper` and create a new repository there.
This repository will be empty: this is perfectly normal.
You will import starter code in a later step.

[IMPORTANT]
====
Regularly push your project code to GitHub.

This is a safety measure against technical mishaps.
If you were to lose your hard work and have failed to push your code frequently, expect no compassion from us.
====

## Getting the Starter Code

In order to get the starter code and to be able to receive future updates, you need to link your repository to my original repository.
Inside your local repository (i.e., inside the `minesweeper` directory):

[source,bash]
----
# Needs to happen only once
$ git remote add upstream https://github.com/ucll-vgo/minesweeper-starter
----

Pull in the starter code using the command below:

[source,bash]
----
$ git pull upstream master
----

Note that this same command also allows you to pull in updates.

[IMPORTANT]
====
It is your responsibility to download updates as they become available.
You can ask GitHub to notify you whenever an update is made to the repository using the watch functionality (top right corner) provided on the https://github.com/ucll-vgo/minesweeper-starter[repository's website].
====
